%% function [levelEncoded_data name role levels]=openExampleSet(exampleSet)
% 
% This function extracts the data from the given variable generated by
% Octave extension for Rapidminer, either using the cell model or the
% struct model. It also checks that the variable is well-formed. Below we
% suppose that the ExampleSet has M examples and N attributes.
%
% INPUTS:
%           exampleSet : a {3xN} cell or a struct matching the "Octave
%                        extension for Rapidminer" data model. See
%                        "openCellExampleSet" and "openStructExampleSet"
%                        for details.
%
% OUTPUTS:
%          name: 
%                   a 1xN cell containing the attribute names
%          role: 
%                   a 1xN cell containing the attribute roles (such as
%                   'regular', 'weight', 'label', etc.). Might be empty.
%
%          levelEncoded_data: 
%                   a MxN array containing the whole example set with all
%                   attributes encoded as numeric values. Numeric
%                   attributes' contents are taken as is, whereas for
%                   nominal attributes a dictionary of possible levels is
%                   created automatically and stored in 'levels'. In such
%                   case the corresponding column in levelEncoded_data
%                   contains the indices of the attribute values in the
%                   corresponding dictionary
%          levels:
%                   a 1xN cell containing the dictionary created for the
%                   nominal attributes. The dictionary may be empty (for
%                   numeric attributes), or may be a cell (general case
%                   where the levels are strings arrays), or may be an
%                   array (for nominal attributes with numeric levels).
%
%
% Authors: Yaoyu Zhang, Sylvain Marié
% Last modified: 23/07/12
%%
function [levelEncoded_data name role levels]=openExampleSet(exampleSet)
	
	if (iscell(exampleSet) == 1);
	
		[levelEncoded_data name role levels]=openCellExampleSet(exampleSet);
		
    elseif (isstruct(exampleSet) == 1);
	
		[levelEncoded_data name role levels]=openStructExampleSet(exampleSet);
		
    else
		error(['Error: type: input arguments must be Cell or Struct, found ' class(exampleSet)])
	end
	
end